= How to Use Emmy

:uri-QUICKSTART: https://github.com/emmy/emmy#quickstart

== Emmy Supported Environments

This section, like many others in the docs at the moment, is quite sparse. This
will change in the coming months!

Emmy is best experienced in an interactive environment like the
https://clojure.org/guides/repl/introduction[Clojure REPL]. We support a number
of environments with rich support for https://en.wikipedia.org/wiki/TeX[TeX]
rendering and plotting. These are catalogued below., paired with "Getting
Started" instructions.

After setting up your environment with any of the listed methods, visit the
{uri-QUICKSTART}[Emmy Quickstart] to get some ideas about how to use the
library.

=== Clojure(script) REPL

Install Emmy into your Clojure(script) project using the instructions at
its Clojars page:

image::https://img.shields.io/clojars/v/emmy/emmy.svg[caption="Emmy Clojars Project", link="https://clojars.org/emmy/emmy"]

Initialize the `emmy.env` "Batteries Included" environment at the REPL:

```clojure
(require '[emmy.env :as env])
(env/bootstrap-repl!)
```

And

=== Nextjournal

You can access all Emmy namespaces from any
https://nextjournal.com[Nextjournal] page by typing

[source, clojure]
----
```cljs
----

and hitting ``<space>`` in any block, and evaluating the following form:

[source, clojure]
----
(nextjournal.env/load! :emmy)
----

Any subsequent ClojureScript block will have every function in
https://cljdoc.org/d/emmy/emmy/CURRENT/api/emmy.env[``emmy.env``]
available.

Visit the https://nextjournal.com/try/samritchie/emmy[Emmy Tutorial on
Nextjournal] to try all of the examples in the {uri-QUICKSTART}[Quickstart] in
your browser with no setup required.

Many of the exercises from https://tgvaughan.github.io/sicm/[Structure and
Interpretation of Classical Mechanics] exist in Nextjournal form at
https://nextjournal.com/sicm[the Nextjournal SICM directory]. To try any of
these notebooks without creating an account:

- Click on one you find interesting, like https://nextjournal.com/sicm/ch-9-our-notation
- Modify the URL by inserting "/try/" before "sicm", turning the above URL into
  https://nextjournal.com/try/sicm/ch-9-our-notation

All cells on this new page will be interactive.

=== Planned Environments

Many of these are working but undocumented. Check back, or file an issue to get
more details.

Working:

- Emacs https://orgmode.org/[Org Mode]
- Scicloj's https://github.com/scicloj/notespace[Notespace]
- https://jupyter.org[Jupyter Notebooks] via
  https://github.com/clojupyter/clojupyter[Clojupyter]

Planned:

- https://www.texmacs.org/tmweb/home/welcome.en.html[GNU TeXmacs]
- the https://github.com/metasoarous/oz[Oz] library, built around Vega and
  Vega-Lite
- http://gorilla-repl.org[Gorilla REPL]
- https://github.com/mhuebert/maria[Maria]
- https://vlaaad.github.io/reveal/[Reveal] for Clojure
- Standalone shell application via https://www.graalvm.org[GraalVM]
