= Getting Involved / What's Missing?

== Getting Involved / What's Missing?

Here's a short overview. More info coming soon!

=== Developing in Emmy

To run all tests in Clojure, you'll need to install the
https://clojure.org/guides/install_clojure[Clojure CLI tool]. The ClojureScript
tests require https://nodejs.org/en/[Node.js]. If you're on a Mac, install
https://brew.sh[Homebrew]:

[source, bash]
----
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
----

Then run

[source, bash]
----
brew install node clojure/tools/clojure
----

To get both dependencies.

deps.edn projects are configured by layering the various "aliases" defined in
`deps.edn`. For example:

- `clj` (or `clojure`) called by itself will activate a REPL with the project's
core dependencies available.
- `clj -A:test` will layer in the options specified in the `:test` entry under
  `:aliases` in `deps.edn`; in this case, the `test` directory and the
  dependencies required to run tests. `clj -X:test:runner` will additionally
  layer in the `:runner` entry AND execute the `:exec-fn` specified.

See the https://clojure.org/guides/deps_and_cli[Clojure Deps and CLI Guide] for
more details.

=== Clojure Tests

To run the full Clojure test suite:

[source, bash]
----
clojure -P -M:test:runner
----

=== ClojureScript Tests

We run the ClojureScript test suite and check for advanced compilation warnings
using [shadow-cljs].

In the ``emmy`` directory, run

[source, bash]
----
npm install
----

to run the full ClojureScript test suite, call the following command (and make
sure to note any warnings):

[source, bash]
----
npm run test
----

The following command will start a process that recompiles the project when any
file changes:

[source, bash]
----
shadow-cljs watch test
----

=== Linting with clj-kondo

We use https://github.com/clj-kondo/clj-kondo[clj-kondo] to lint the project. To
run the linter from the JVM, run:

[source, bash]
----
clojure -M:test:lint --lint src:test
----

Or, install the binary by following
https://github.com/clj-kondo/clj-kondo/blob/master/doc/install.md[this
instructions] and lint with the following command:

[source, bash]
----
clj-kondo --lint src:test
----

=== Code Coverage

https://github.com/cloverage/cloverage[Cloverage] generates coverage reports for
every pull request and the main branch in the repository. Coverage reports live
at https://codecov.io/github/emmy/emmy[codecov.io].

To invoke cloverage, call

[source, bash]
----
clojure -M:test:coverage <args-to-cloverage>
----

=== Jars & Releases

We use Clojure's https://clojure.org/guides/tools_build[tools.build] system to
produce and publish jars. This is configured in ``build.clj``.

The library's current version is set by ``resources/EMMY_VERSION``.

The following command will produce a jar of the form
``target/emmy-<version>.jar``:

[source, bash]
----
clojure -T:build jar
----

Optionally, supply a suffix like ``:version-suffix "SOMETHING"`` to append
``-SOMETHING`` to the version.

To generate the jar and install it to the local Maven cache, run

[source, bash]
----
clojure -T:build install
----

Deploying to Clojars requires the ``CLOJARS_USERNAME`` and ``CLOJARS_PASSWORD``
variables to be set. Once those are configured, run

[source, bash]
----
clojure -T:build publish
----

To push the latest code to Clojars. Only one push per release is allowed, while
snapshots can be pushed multiple times (overwriting the previous SNAPSHOT
build).
