= FAQ
:toc: right
:toclevels: 2

== FAQ

=== Who is using Emmy?

- https://github.com/kloimhardt[@kloimhardt] has integrated Emmy into his
  https://scratch.mit.edu[Scratch]-like, blocks-based language at
  https://github.com/kloimhardt/clj-tiles[clj-tiles]. See
  https://kloimhardt.github.io/cljtiles.html?page=freeparticle[this demo] for a
  lovely example of Lagrangian Mechanics in ``clj-tiles``.

- @light-matters and @MagusMachinae are collaborating on
  [Peek](https://gitlab.com/LightMatters/peek): "A Clojure implementation of
  symbolic quantum mechanics, or, as it could be called, measurement mechanics.
  The current name reflects my idea of one of the, if not most, distinguishing
  features of quantum mechanics: that observation changes the result."

=== How should I configure Emacs?

The Emmy repository includes a
https://github.com/emmy/emmy/blob/main/.dir-locals.el[dir-locals.el]
file with a few variable settings that improve the Emacs experience with
Emmy.

The main interesting dir-local variable to set is ``cider-print-fn``:

[source, elisp]
----
((nil
  . ((cider-print-fn . "emmy.expression/expression->stream"))))
----

Setting CIDER's print function to ``expression->stream`` will cause the REPL to
automatically simplify forms before rendering them.

``expression->stream`` currently uses ``clojure.pprint`` to print simplified
values. Once https://github.com/emmy/emmy/issues/519[#519] is
completed, the ``pprint`` call will be replaced by a call you can bind to
``prn``, ``zprint`` or any other preferred printer.
