= Introduction to SICMUtils

:status:
:uri-SICM: http://mitpress.mit.edu/books/structure-and-interpretation-classical-mechanics
:uri-FDG: http://mitpress.mit.edu/books/functional-differential-geometry
:uri-SICP: http://mitpress.mit.edu/sicp/
:uri-GSCM: http://www.cs.rochester.edu/~gildea/guile-scmutils/
:uri-LEIN: http://leiningen.org
:uri-REFMAN: https://groups.csail.mit.edu/mac/users/gjs/6946/refman.txt

== sicmutils

A Clojure(script) implementation of the {uri-REFMAN}[Scmutils] system for math
and physics investigations in the Clojure language.

Scmutils is extensively used in the textbooks {uri-SICM}[The Structure and
Interpretation of Classical Mechanics] and {uri-FDG}[Functional Differential
Geometry] by G.J. Sussman and J. Wisdom.

TIP: Need help getting started? Say hi on https://twitter.com/sritchie[Twitter]
or http://clojurians.net/[Clojurians Slack] in
https://clojurians.slack.com/archives/C01ECA9AA74[#sicmutils].

image:https://github.com/sicmutils/sicmutils/workflows/Clojure%20CI/badge.svg?branch=main[Build Status, link=https://github.com/sicmutils/sicmutils/actions?query=workflow%3A%22Clojure+CI%22]
image:https://img.shields.io/codecov/c/github/sicmutils/sicmutils/main.svg?maxAge=3600[Codecov branch, link=https://codecov.io/github/sicmutils/sicmutils]
image:https://cljdoc.org/badge/sicmutils/sicmutils[cljdoc badge, link=https://cljdoc.org/d/sicmutils/sicmutils/CURRENT]
image:https://img.shields.io/clojars/v/sicmutils/sicmutils.svg[Clojars Project, link=https://clojars.org/sicmutils/sicmutils]

== Quickstart

Install SICMUtils into your Clojure(script) project using the instructions at
its Clojars page:

image::https://img.shields.io/clojars/v/sicmutils/sicmutils.svg[Clojars Project, link=https://clojars.org/sicmutils/sicmutils]

Initialize a REPL and simplify a trigonometric identity:

[source, clojure]
----
user=> (require '[sicmutils.env :as env])
user=> (env/bootstrap-repl!)
user=> (def render (comp ->infix simplify))
user=> (render
        (+ (square (sin 'x))
           (square (cos 'x))))
1
----

Define a Lagrangian and generate the Lagrange equations of motion for the
physical system it describes, rendered in polar coordinates:

[source, clojure]
----
(defn L-central-polar [m U]
  (fn [[_ [r] [rdot φdot]]]
    (- (* 1/2 m
          (+ (square rdot)
             (square (* r φdot))))
       (U r))))
#'user/L-central-polar

user=>
(let [potential-fn (literal-function 'U)
      L     (L-central-polar 'm potential-fn)
      state (up (literal-function 'r)
                (literal-function 'φ))]
  (render
   (((Lagrange-equations L) state) 't)))
"down(- m (Dφ(t))² r(t) + m D²r(t) + DU(r(t)), 2 m Dφ(t) r(t) Dr(t) + m (r(t))² D²φ(t))"
----

Confused? You're not alone! This is a very dense library, and not well
documented (yet). Some suggested next steps, for now:

* We've ported the original {uri-REFMAN}[SCMUtils Reference Manual] over to
  SICMUtils. Visit the link:refman.adoc[SICMUtils Reference Manual] for a
  comprehensive overview of SICMUtils.
* Clone this repository and run `lein repl` for a batteries included REPL
  environment. All of the examples in the link:refman.adoc[SICMUtils refman]
  will work.
* Browse the table of contents on the left hand side. Many of the pages are
  populated with good information, and we're working hard to flesh this out
  further.
* For a deep dive into classical mechanics using this library, visit the HTML
  version of https://tgvaughan.github.io[Structure and Interpretation of
  Classical Mechanics]. Follow along with the solutions at
  link:https://github.com/sritchie/sicm[@sritchie's SICM solutions repository.]

== Background

{uri-SICM}[SICM] and {uri-FDG}[FDG] can be thought of as spiritual successors to
{uri-SICP}[The Structure and Interpretation of Computer Programs], a very
influential text—as I can attest, since carefully reading this book in my 30s
changed my life as a programmer. To see the same techniques applied to
differential geometry and physics is an irresistible lure.

Scmutils is an excellent system, but it is written in an older variant of LISP
(Scheme) and is tied to a particular implementation of Scheme—MIT/GNU Scheme.
(There is a {uri-GSCM}[port to Guile], but due to the fact that Guile does not
support MIT Scheme's
https://www.gnu.org/software/mit-scheme/documentation/stable/mit-scheme-ref/Application-Hooks.html[apply
hooks] some glue code is required to run examples from the book in that
environment.)

Having the system in Clojure offers a number of advantages. It is not necessary
to obtain or prepare a MIT/GNU Scheme executable to execute: only a Java runtime
is required. It does not require the X Window System for graphics, as MIT Scheme
does. All of the standard tooling for Java and Clojure become available, and
this is a lot compared to what we get with MIT/GNU scheme. Clojure support is
now extensive in any number of editors and IDEs. Even better, you can interact
with the system in the context of a link:/jupyter[Jupyter notebook].

You can invoke the system from within Java or JS code, or use any Java or JS
packages you like together with the mathematics system. It's my hope that
continuing this project will extend the reach of SICM and FDG by allowing
experimentation and collaboration with them in modern environments.

== Next Steps

Please explore the documentation, and send us (`@sritchie`, `@colins`) in
particular a note in the
https://clojurians.slack.com/archives/C01ECA9AA74[#sicmutils channel on
Clojurians slack] if you'd like to talk or have any questions at all!
