#!/usr/bin/env bash
# THIS SCRIPT IS RAN AS PART OF LIBRARY's CI PIPELINES
# ANY CHANGES SHOULD BE TESTED WITH EXTRA CARE

cljdoc_edn_path="$1"
list=$(cat "$cljdoc_edn_path" |  grep ':file' | awk -F '\:file' '{print $2}' | awk -F '"' '{print $2}')
fail=0

while read -r line; do
if [ ! -f "$line" ]; then
  echo "File $line is referenced in cljdoc.edn but not present"
  fail=1
fi
done <<< "$list";

exit $fail
